services:
  caddy:
    image: caddy:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client
      - server
  client:
    image: ghcr.io/xuatz/breakout-shuffler/client:latest
    environment:
      - VITE_API_URL=https://server.breakout.local
    expose:
      - "3000"
  server:
    image: ghcr.io/xuatz/breakout-shuffler/server:latest
    expose:
      - "9000"
  redis:
    image: redis:latest

volumes:
  caddy_data:
  caddy_config:
